const Text = {
    1 : "Quantum physics is a branch of physics that explores the behavior of matter and energy at the smallest scales—specifically, at the level of atoms and subatomic particles. Unlike classical physics, quantum physics reveals that particles can exist in multiple states at once (superposition) and that their properties are fundamentally probabilistic rather than deterministic. Key concepts include wave-particle duality, quantum entanglement, and uncertainty. Quantum physics has revolutionized our understanding of the universe and has applications in technologies like quantum computing, cryptography, and medical imaging.",
    2 : "The Indian Space Research Organisation (ISRO) is India's national space agency, renowned for its advancements in space exploration, satellite development, and space research. Founded in 1969, ISRO has made significant strides in space technology, launching satellites for communication, weather forecasting, and navigation. It gained global attention with missions like Chandrayaan (India's lunar exploration program) and Mangalyaan (India's Mars Orbiter Mission), becoming the first country to reach Mars on its maiden attempt. ISRO is also known for its cost-effective missions and is a major player in the global space industry.",
    3 : "The Polar Satellite Launch Vehicle (PSLV) is a highly successful launch vehicle developed by the Indian Space Research Organisation (ISRO). First launched in 1993, PSLV has become ISRO's workhorse for deploying satellites into polar, geostationary, and low Earth orbits. It is known for its reliability and versatility, with the capability to carry multiple satellites in a single mission. The PSLV has been used for significant missions like launching India's Chandrayaan and Mangalyaan, as well as deploying numerous international satellites, establishing ISRO as a key player in the global space launch market.",
    4 : "Adolf Hitler was a German politician and dictator who led the National Socialist German Workers' Party (Nazi Party) and became Chancellor of Germany in 1933. He later assumed the title of Führer, establishing a totalitarian regime. Hitler's aggressive expansionist policies led to World War II, and his ideology of Aryan racial superiority resulted in the Holocaust, where millions of Jews and other minorities were systematically persecuted and murdered. Hitler's reign ended in 1945 with Germany's defeat in the war, and he died by suicide in his Berlin bunker. His legacy is one of destruction and atrocity.",
    5 : "Programming is the process of designing, writing, testing, and maintaining code that enables computers and software to perform specific tasks. It involves using programming languages like Python, Java, C++, and JavaScript to communicate instructions to a machine. Programmers create algorithms and solve problems through logical thinking and coding, which can range from developing applications and websites to controlling hardware and managing data. Programming plays a critical role in technology, powering everything from smartphones and websites to artificial intelligence and automation systems. It's a foundational skill in today's digital world.",
    6 : "India is a diverse and culturally rich country located in South Asia. It is the seventh-largest country by land area and the second-most populous, with over 1.4 billion people. India is known for its rich history, dating back thousands of years, with significant contributions to art, science, mathematics, and philosophy. It is home to major world religions like Hinduism, Buddhism, Jainism, and Sikhism. The country gained independence from British rule in 1947 and is now a democratic republic. India has a fast-growing economy, with key industries in information technology, agriculture, and manufacturing. Its cultural diversity is reflected in its many languages, festivals, and traditions.",
    7 : "OpenAI is an advanced artificial intelligence research organization dedicated to ensuring that AI benefits all of humanity. Founded in 2015, OpenAI aims to create safe and beneficial AI systems while also making sure that these technologies are accessible and widely shared. It is known for developing state-of-the-art AI models, including language models like GPT (Generative Pre-trained Transformer), which excel at tasks like natural language processing, translation, and content generation. OpenAI also focuses on AI safety, ethical AI use, and collaboration with industry and governments to regulate AI for the public good.",
    8 : "The Defence Research and Development Organisation (DRDO) is India's premier agency responsible for research and development in defense technologies. Established in 1958, DRDO operates under the Ministry of Defence and focuses on enhancing India's self-reliance in defense capabilities. It works on a wide range of technologies, including missiles, radars, electronic warfare systems, combat vehicles, and military aircraft. DRDO has been pivotal in developing indigenous defense systems like the Agni and Prithvi missile series, fighter aircraft like the Tejas, and the Arjun main battle tank. Its contributions strengthen India's defense preparedness and technological advancement in military capabilities.",
    9 : "The Russia-Ukraine war began in February 2022 when Russia launched a large-scale military invasion of Ukraine, escalating a conflict that had started in 2014 with Russia’s annexation of Crimea and its support for separatists in eastern Ukraine. The invasion has resulted in widespread destruction, civilian casualties, and a humanitarian crisis. Ukraine, backed by Western nations through economic sanctions on Russia and military aid to Kyiv, has mounted a strong defense. The war has significantly impacted global geopolitics, energy markets, and food supplies, as both nations are major exporters of grain and energy. Despite multiple rounds of negotiations, a resolution remains elusive as of 2025."
};
export {Text};